#!/usr/bin/env python


from circuits.web import Server, Controller


class Root(Controller):

    def index(self):
        return "Hello World!"


def main():
    Server(("0.0.0.0", 80) + Root()).run()


if __name__ == "__main__":
    main()
